const mapRouter = Object.freeze({
  '/document/alert': 'alert',
  '/document/anchor': 'anchor',
  '/document/avatar': 'avatar',
  '/document/badge': 'badge',
  '/document/breadcrumb': 'breadcrumb',
  '/document/button': 'button',
  '/document/carousel': 'carousel',
  '/document/checkbox': 'checkbox',
  '/document/chip': 'chip',
  '/document/collapse': 'collapse',
  '/document/confirm': 'confirm',
  '/document/divider': 'divider',
  '/document/drawer': 'drawer',
  '/document/form': 'form',
  '/document/icon': 'icon',
  '/document/inputnumber': 'inputnumber',
  '/document/loader': 'loader',
  '/document/menu': 'menu',
  '/document/modal': 'modal',
  '/document/notification': 'notification',
  '/document/pagination': 'pagination',
  '/document/password': 'password',
  '/document/popover': 'popover',
  '/document/progress': 'progress',
  '/document/radio': 'radio',
  '/document/rater': 'rater',
  '/document/select': 'select',
  '/document/skeleton': 'skeleton',
  '/document/slider': 'slider',
  '/document/stepper': 'stepper',
  '/document/switch': 'switch',
  '/document/tabs': 'tabs',
  '/document/textarea': 'textarea',
  '/document/textbox': 'textbox',
  '/document/timeline': 'timeline',
  '/document/tooltip': 'tooltip',
  '/document/typography': 'typography',
});

export default mapRouter;
